--- # 서버 세팅
server:
    port: 9978

--- # jsp 경로 설정
spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

--- # 개발 세팅
spring:
    devtools:
        # html, jsp 같은 컴파일이 필요없는 파일 라이브 리로드
        livereload:
            enabled: true
        # 자바코드 수정시 enabled
        restart:
            enabled: true